# Generated by Django 2.0.5 on 2018-09-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelfinder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating_CLEANLINESS',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating_LOCATION',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating_SERVICE',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating_VALUE',
        ),
    ]
