# Generated by Django 2.0.5 on 2018-09-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelfinder', '0003_auto_20180907_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='city',
        ),
    ]
